logging:
  level:
    org.flowable.ui.modeler.rest.app: debug
    org.flowable: debug
#    root: debug
server:
  port: 8080
#  servlet:
#    context-path: "/flowable-modeler-demo"
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:workflow}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useOldAliasMetadataBehavior=true
    #      url: jdbc:log4jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:yongyu_lms2}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useOldAliasMetadataBehavior=true
    username: ${DB_USER:root}
    password: ${DB_PWD:942464Yy}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: flowable-modeler-demo


mybatis-plus:
#  type-aliases-package: com.example.oldguy.modules.app.dao.**
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations:
      - classpath:com.example.oldguy.**/*.xml
    global-config:
      db-config:
        id-type: INPUT
